# Generated by Django 5.2.4 on 2025-07-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.IntegerField(help_text='Left value of the Nested Set')),
                ('rgt', models.IntegerField(help_text='Right value of the Nested Set')),
                ('children_count', models.IntegerField(default=0, help_text='Number of direct children')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'db_table': 'nodes',
            },
        ),
    ]
