# Generated by Django 5.2.4 on 2025-07-20 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetree',
            name='lft',
            field=models.IntegerField(help_text='Right value of the Nested Set  '),
        ),
        migrations.AlterField(
            model_name='nodetree',
            name='rgt',
            field=models.IntegerField(help_text='Left value of the Nested Set'),
        ),
        migrations.CreateModel(
            name='NodeTreeNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text="Language code (e.g., 'en', 'it')", max_length=10)),
                ('nodeName', models.CharField(help_text='Name of the node in the specified language', max_length=255)),
                ('nodeTree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='nodes.nodetree')),
            ],
            options={
                'verbose_name': 'Node Name',
                'verbose_name_plural': 'Node Names',
                'db_table': 'node_tree_names',
                'indexes': [models.Index(fields=['language'], name='node_tree_n_languag_ed8bf5_idx'), models.Index(fields=['nodeTree', 'language'], name='node_tree_n_nodeTre_ab17db_idx')],
                'unique_together': {('nodeTree', 'language')},
            },
        ),
    ]
